version: '3.8'

services:
  postgres:
    container_name: postgres
    image: postgres:16
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: gui
      POSTGRES_PASSWORD: 123123
      POSTGRES_DB: app
    volumes:
      - ./data/pg:/data/postgres

  redis:
    container_name: redis
    image: redis:7
    ports:
      - 6379:6379
